# Generated by Django 4.2.3 on 2023-09-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(default='Niloy-Blogs', max_length=200),
        ),
    ]
