# Generated by Django 4.2.3 on 2023-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
