# Generated by Django 4.2.3 on 2023-09-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpost_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='phitron', max_length=100),
        ),
    ]
