# Generated by Django 4.2.3 on 2023-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blogpost_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Web_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
