# Generated by Django 4.2.3 on 2023-09-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_profile_profile_image_profile_web_url_profile_fb_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Web_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb_url',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, default='https://bd.linkedin.com/', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='web_url',
            field=models.CharField(blank=True, default='http://niloysarkar.pythonanywhere.com/', max_length=200, null=True),
        ),
    ]
