# Generated by Django 4.2.3 on 2023-09-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_blogpost_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='favourites',
        ),
    ]
